/**
 * Sample API v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Represents an article.
 */
export interface Article { 
    /**
     * The unique number of the article.
     */
    number: number;
    /**
     * The name of the article.
     */
    name: string;
    /**
     * An optional description of the article.
     */
    description?: string;
    /**
     * The price of the article.
     */
    price: number;
}