/**
 * Sample API v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Represents a weather forecast.
 */
export interface WeatherForecast { 
    /**
     * The date this forecast applies to.
     */
    date?: Date;
    /**
     * The forecast temperature in degrees Celsius.
     */
    temperatureC?: number;
    /**
     * The forecast temperature in degrees Fahrenheit.
     */
    readonly temperatureF?: number;
    /**
     * A brief textual description of the forecast.
     */
    summary?: string;
}